package cli

import (
	"context"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/HugoAlvarezAjenjo/pulse/internal/result"
	"github.com/HugoAlvarezAjenjo/pulse/internal/runner"
)

var reportCmd = &cobra.Command{
	Use:   "report",
	Short: "Run checks and generate a markdown report",
	Long:  "Executes all checks and outputs a shareable markdown report to stdout or a file.",
	RunE:  runReport,
}

var flagReportFile string

func init() {
	reportCmd.Flags().StringVar(&flagReportFile, "file", "", "write report to file instead of stdout")
}

func runReport(cmd *cobra.Command, args []string) error {
	ctx := context.Background()

	cfg, err := loadConfig()
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %s\n", err)
		os.Exit(2)
	}

	checkList, err := buildChecks(cfg)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: %s\n", err)
		os.Exit(2)
	}

	if len(flagGroups) > 0 {
		checkList = filterByGroups(cfg, checkList, flagGroups)
	}

	r := runner.New()
	if timeout, err := time.ParseDuration(flagTimeout); err == nil {
		r.Timeout = timeout
	}

	start := time.Now()
	results := r.RunWithTimeouts(ctx, checkList)
	duration := time.Since(start)

	report := generateMarkdown(results, duration)

	if flagReportFile != "" {
		if err := os.WriteFile(flagReportFile, []byte(report), 0644); err != nil {
			fmt.Fprintf(os.Stderr, "error: writing report: %s\n", err)
			os.Exit(2)
		}
		fmt.Printf("Report written to %s\n", flagReportFile)
	} else {
		fmt.Print(report)
	}

	os.Exit(exitCode(results))
	return nil
}

func generateMarkdown(results []result.Result, duration time.Duration) string {
	var b strings.Builder

	passed := 0
	failed := 0
	errors := 0
	for _, r := range results {
		switch r.Status {
		case result.Success:
			passed++
		case result.Failure:
			failed++
		case result.Error:
			errors++
		}
	}

	b.WriteString("# Pulse Environment Report\n\n")
	b.WriteString(fmt.Sprintf("**Summary:** %d passed, %d failed, %d errors — %s\n\n", passed, failed, errors, formatReportDuration(duration)))

	// Status badge
	if failed == 0 && errors == 0 {
		b.WriteString("✅ **All checks passed**\n\n")
	} else {
		b.WriteString("❌ **Environment has issues**\n\n")
	}

	// Results table
	b.WriteString("| Status | Check | Details |\n")
	b.WriteString("|--------|-------|----------|\n")

	for _, r := range results {
		icon := "✓"
		switch r.Status {
		case result.Failure:
			icon = "✗"
		case result.Error:
			icon = "!"
		}

		detail := r.Message
		if r.Hint != "" && r.Status != result.Success {
			detail = r.Hint
		}

		b.WriteString(fmt.Sprintf("| %s | %s | %s |\n", icon, r.Name, detail))
	}

	// Failures detail
	if failed > 0 || errors > 0 {
		b.WriteString("\n## Issues\n\n")
		for _, r := range results {
			if r.Status == result.Success {
				continue
			}
			b.WriteString(fmt.Sprintf("### %s\n\n", r.Name))
			if r.Message != "" {
				b.WriteString(fmt.Sprintf("- **Error:** %s\n", r.Message))
			}
			if r.Hint != "" {
				b.WriteString(fmt.Sprintf("- **Hint:** %s\n", r.Hint))
			}
			if r.Fix != nil {
				b.WriteString(fmt.Sprintf("- **Fix:** `%s`\n", r.Fix.Run))
			}
			b.WriteString("\n")
		}
	}

	b.WriteString("\n---\n*Generated by [Pulse](https://github.com/HugoAlvarezAjenjo/pulse)*\n")

	return b.String()
}

func formatReportDuration(d time.Duration) string {
	if d < time.Second {
		return fmt.Sprintf("%dms", d.Milliseconds())
	}
	return fmt.Sprintf("%.1fs", d.Seconds())
}
